# Site wide configuration

title: "夏令的博客"
description: "记录那些技术与人文点滴-心向远方"
logo: photo.jpg # 120x120 px default image used for Twitter summary card
teaser: teaser/teaser.jpg # 400x250 px default teaser image used in image archive grid
locale:
url:

default:                       
    -
        scope:                 
            type: "article"    
        values:                
            ads: false         
            toc: false         


# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: xialingsc(夏令)
  email: xialingsc@gmail.com
  twitter: lingsc
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: photo.jpg # 160x160 px image for author byline
disqus-shortname: xialingsc


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
