# Site wide configuration

title:"夏令的博客"
description:"记录那些技术与人文点滴，心向远方"
logo:photo.jpg # 120x120 px default image used for Twitter summary card
teaser:default.jpg # 400x250 px default teaser image used in image archive grid
locale:
url:

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name:xialingsc(夏令)
  email:xialingsc@gmail.com
  twitter:
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:xialingsc


